<?php

namespace AppBundle\Entity;

/**
 * AppBundle/Repository/PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppBundle/Repository/PlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
